"""add scadenze fields

Revision ID: add_scadenze_fields
Revises: c19718caa743
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_scadenze_fields'
down_revision = 'c19718caa743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Aggiungi campi per scadenze furgoni
    op.add_column('furgoni', sa.Column('scadenza_bollo_identificativo', sa.String(), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_bollo_frazionamento', sa.Enum('mensile', 'semestrale', 'annuale', name='frazionamento'), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_bollo_assicuratore', sa.String(), nullable=True))
    
    op.add_column('furgoni', sa.Column('scadenza_revisione_identificativo', sa.String(), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_revisione_frazionamento', sa.Enum('mensile', 'semestrale', 'annuale', name='frazionamento'), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_revisione_assicuratore', sa.String(), nullable=True))
    
    op.add_column('furgoni', sa.Column('scadenza_rca_identificativo', sa.String(), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_rca_frazionamento', sa.Enum('mensile', 'semestrale', 'annuale', name='frazionamento'), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_rca_assicuratore', sa.String(), nullable=True))
    
    op.add_column('furgoni', sa.Column('scadenza_infortuni_conducente_identificativo', sa.String(), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_infortuni_conducente_frazionamento', sa.Enum('mensile', 'semestrale', 'annuale', name='frazionamento'), nullable=True))
    op.add_column('furgoni', sa.Column('scadenza_infortuni_conducente_assicuratore', sa.String(), nullable=True))
    
    # Aggiungi campi per scadenze gommoni
    op.add_column('gommoni', sa.Column('scadenza_rca_identificativo', sa.String(), nullable=True))
    op.add_column('gommoni', sa.Column('scadenza_rca_frazionamento', sa.Enum('mensile', 'semestrale', 'annuale', name='frazionamento'), nullable=True))
    op.add_column('gommoni', sa.Column('scadenza_rca_assicuratore', sa.String(), nullable=True))
    
    op.add_column('gommoni', sa.Column('scadenza_manutenzione_identificativo', sa.String(), nullable=True))
    op.add_column('gommoni', sa.Column('scadenza_manutenzione_frazionamento', sa.Enum('mensile', 'semestrale', 'annuale', name='frazionamento'), nullable=True))
    op.add_column('gommoni', sa.Column('scadenza_manutenzione_assicuratore', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rimuovi campi per scadenze furgoni
    op.drop_column('furgoni', 'scadenza_infortuni_conducente_assicuratore')
    op.drop_column('furgoni', 'scadenza_infortuni_conducente_frazionamento')
    op.drop_column('furgoni', 'scadenza_infortuni_conducente_identificativo')
    
    op.drop_column('furgoni', 'scadenza_rca_assicuratore')
    op.drop_column('furgoni', 'scadenza_rca_frazionamento')
    op.drop_column('furgoni', 'scadenza_rca_identificativo')
    
    op.drop_column('furgoni', 'scadenza_revisione_assicuratore')
    op.drop_column('furgoni', 'scadenza_revisione_frazionamento')
    op.drop_column('furgoni', 'scadenza_revisione_identificativo')
    
    op.drop_column('furgoni', 'scadenza_bollo_assicuratore')
    op.drop_column('furgoni', 'scadenza_bollo_frazionamento')
    op.drop_column('furgoni', 'scadenza_bollo_identificativo')
    
    # Rimuovi campi per scadenze gommoni
    op.drop_column('gommoni', 'scadenza_manutenzione_assicuratore')
    op.drop_column('gommoni', 'scadenza_manutenzione_frazionamento')
    op.drop_column('gommoni', 'scadenza_manutenzione_identificativo')
    
    op.drop_column('gommoni', 'scadenza_rca_assicuratore')
    op.drop_column('gommoni', 'scadenza_rca_frazionamento')
    op.drop_column('gommoni', 'scadenza_rca_identificativo')
    
    # ### end Alembic commands ###
