"""trainings: add fields + indexes

Revision ID: b90f227d6985
Revises: 
Create Date: 2025-08-12 20:40:28.676604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90f227d6985'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allenamenti', sa.Column('time_start', sa.Time(), nullable=True))
    op.add_column('allenamenti', sa.Column('time_end', sa.Time(), nullable=True))
    op.add_column('allenamenti', sa.Column('recurrence', sa.String(length=20), nullable=True))
    op.add_column('allenamenti', sa.Column('repeat_until', sa.Date(), nullable=True))
    op.add_column('allenamenti', sa.Column('barca_id', sa.Integer(), nullable=True))
    op.add_column('allenamenti', sa.Column('coach_id', sa.Integer(), nullable=True))
    op.create_index('idx_allenamenti_barca', 'allenamenti', ['barca_id'], unique=False)
    op.create_index('idx_allenamenti_coach', 'allenamenti', ['coach_id'], unique=False)
    op.create_index('idx_allenamenti_date', 'allenamenti', ['data'], unique=False)
    op.create_foreign_key(None, 'allenamenti', 'barche', ['barca_id'], ['id'])
    op.create_foreign_key(None, 'allenamenti', 'users', ['coach_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'allenamenti', type_='foreignkey')
    op.drop_constraint(None, 'allenamenti', type_='foreignkey')
    op.drop_index('idx_allenamenti_date', table_name='allenamenti')
    op.drop_index('idx_allenamenti_coach', table_name='allenamenti')
    op.drop_index('idx_allenamenti_barca', table_name='allenamenti')
    op.drop_column('allenamenti', 'coach_id')
    op.drop_column('allenamenti', 'barca_id')
    op.drop_column('allenamenti', 'repeat_until')
    op.drop_column('allenamenti', 'recurrence')
    op.drop_column('allenamenti', 'time_end')
    op.drop_column('allenamenti', 'time_start')
    # ### end Alembic commands ###
